spring:
  application:
    name: student-onb-svc
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


  datasource:
    url: jdbc:postgresql://localhost:5432/student_onboarding
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# ?? Server (student service = port 8080) ???????
server:
  port: 8080

# ?? Session Token Config ???????????????????????
session:
  token-expiry-hours: 24

# ?? CORS ???????????????????????????????????????
cors:
  allowed-origins: http://localhost:4200

# ?? File Storage ???????????????????????????????
file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}

# ?? SpringDoc / Swagger ????????????????????????
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha